vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        livres :
            uri_prefix: /images/couverture
            upload_destination: '%kernel.project_dir%/public/images/couverture'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        utilisateurs :
            uri_prefix: /images/photo_profil
            upload_destination: '%kernel.project_dir%/public/images/photo_profil'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer