controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

liste_formulaire:
    path: '/liste/new'
    controller: 'App\Controller\ListeController::new'